title: My Portfolio
author: Maximilian Rich
email: maximilian.rich@online.de
description: >
  On this website You will find projects I've worked on,
  Skills I've learned, as well as a collection of Posts
  ranging in content that might or might not interest You.
theme: minima
minima:
  skin: dark
github_username: malex5335
show_excerpts: true
plugins:
  - jekyll-seo-tag
