title: Portfolio of Maximilian Rich
author:
  - Maximilian Rich
  - maximilian.rich@online.de
description: A collection of my private projects
theme: minima
minima:
  skin: dark
  show_excerpts: true
  github_username: malex5335
plugins:
  - jekyll-seo-tag
