title: Portfolio of Maximilian Rich
author: Maximilian Rich
email: maximilian.rich@online.de
description: >
  My portfolio displaying projects I've worked on,
  Skills I've learned as well as a collection of Posts
  ranging in content from ideas in my head to mistakes from which I've learned.
theme: minima
minima:
  skin: dark
  show_excerpts: true
  github_username: malex5335
plugins:
  - jekyll-seo-tag
